module.exports = ({
	token: "bot-token-here",
	prefix1: "$getServerVar[prefix]",
	prefix2: "<@bot-user-id>",
	prefix3: "<@!bot-user-id>",
	btr: "botrix",
	topgg: "top.gg",
	bladebl: "blade-bot-list",
	blist: "blist",
	dbleu: "discord-bot-list.eu",
	fateslist: "fates-list",
	ibl: "infinity-bot-list",
	tc: "top-cord",
	voidb: "void-bots",
	statkey: "statcord.com",
	blistspace: "botlist.space",
	botlists: "astro-bot-list",
	bfd: "bots-for-discord",
	dblist: "discord-bot-list.com",
	dlo: "",
	sbl: "space-bot-list",
	ac: "",
	del: "discord-extreme-list",
	port: /*Your server's port*/,
});
